apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: web
  type: ClusterIP # ClusterIP | NodePort | LoadBalancer
  ports:
    - protocol: TCP
      port: 80        # puerto del servicio 
      targetPort: 80  # puerto del container