apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: node-monitor
  labels:
    app: monitoring
spec:
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: node-monitor-container
          image: prom/node-exporter:latest
          ports:
            - containerPort: 9100
