# 1 - namespace
apiVersion: v1
kind: Namespace
metadata:
  name: project-demo
---
#2- configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: project-app-config
  namespace: project-demo
data:
  APP_VERSION: "1.0.0"
  APP_MODE: "production"
---
#3- secret
apiVersion: v1
kind: Secret
metadata:
  name: project-app-secret
  namespace: project-demo
type: Opaque
data:
  USERNAME: YWRtaW4=  ## base64 = admin
  PASSWORD: YWRtaW4xMjM= ## base64 = admin123
---
#4 deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-app-deployment
  namespace: project-demo
  labels:
    app: myproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
    spec: 
      containers:
      - name: project-node-app-container
        image: node:18-alpine
        command: ["sh", "-c", "while true; do echo Running $APP_MODE v$APP_VERSION user: $USERNAME; sleep 10;done"]
        env:
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: project-app-config
              key: APP_MODE
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: project-app-config
              key: APP_VERSION
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: project-app-secret
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: project-app-secret
              key: PASSWORD
---
#5 SERVICE
apiVersion: v1
kind: Service
metadata:
  name: project-app-service
  namespace: project-demo
spec:
  selector:
    app: myproject
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080